apiVersion: v1
kind: Service
metadata:
  name: nodeportsvc
spec:
  selector:
    app: test
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 32000
  type: NodePort


---
apiVersion: v1
kind: Pod
metadata:
  name: hello-python
  labels:
    app: test
spec:
  containers:
    - name: roselan
      image: roselan/test:latest
      ports:
        - containerPort:5000
